### ISSUE TITLE
`i2b2.war` : Could not index Oracle JDBC classes

### ISSUE THREAD

**Issue by akomii** [aktin/debian-i2b2-pkg#14]
During the deployment of the Version `1.8.1` of the `i2b2.war` on Wildfly warning messages are being logged indicating that certain Oracle JDBC classes could not be indexed. 

The i2b2 application is using the PostgreSQL JDBC driver and appears to be functioning correctly despite these warnings. However, it would be preferable to suppress or filter out these Oracle JDBC-related warnings to keep the logs clean.

Tried out versions:
* Wildfly 25 & Postgresql JDBC 42.7.3
* Wildfly 24 & Postgresql JDBC 42.7.1
* Wildfly 18 & Postgresql JDBC 42.2.14
* Wildfly 17 & Postgresql JDBC 42.2.8

```
2024-11-12 11:01:24,761 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0003: Could not index class oracle/jdbc/proxy/oracle$1jdbc$1replay$1driver$1TxnReplayableBase$2oracle$1jdbc$1internal$1OracleTypeMetaData$Arra>
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.FieldInternal.hashCode(FieldInternal.java:99)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.StrongInternPool.hash(StrongInternPool.java:152)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:237)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.NameTable.intern(NameTable.java:117)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.ClassInfo.setFields(ClassInfo.java:745)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.Indexer.index(Indexer.java:1984)
        at org.jboss.as.server@17.0.3.Final//org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
        at org.jboss.as.server@17.0.3.Final//org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
        at org.jboss.as.server@17.0.3.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-11-12 11:01:24,762 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0003: Could not index class oracle/jdbc/proxy/oracle$1jdbc$1replay$1driver$1NonTxnReplayableBase$2oracle$1jdbc$1OracleResultSetMetaData$$$Prox>
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.FieldInternal.hashCode(FieldInternal.java:99)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.StrongInternPool.hash(StrongInternPool.java:152)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:237)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.NameTable.intern(NameTable.java:117)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.ClassInfo.setFields(ClassInfo.java:745)
        at org.jboss.jandex@2.4.1.Final//org.jboss.jandex.Indexer.index(Indexer.java:1984)
        at org.jboss.as.server@17.0.3.Final//org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
        at org.jboss.as.server@17.0.3.Final//org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
        at org.jboss.as.server@17.0.3.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by bunbry** [comment]
The issue is not related to the `i2b2.war` or the Postgresql JDBC. It appears when the Oracle JDBC driver `ojdbc8.jar` is present in the deployment directory of the Wildfly server. It is caused by a Wildfly dependency called Jandex.

It looks like this issue is fixed in Jandex `2.4.3.Final` smallrye/jandex#164 smallrye/jandex#166 . The first Wildfly version which contains a later version of Jandex is Wildfly `27.0.0.Final`.

**Comment by bunbry** [comment]
Are we updating the Wildfly version, or do we ignore the issue for now?

**Comment by akomii** [comment]
We are stuck using Wildfly 22 as this is the last version supporting Java EE8 ([see here](https://docs.wildfly.org/)), the main technology of the AKTIN DWH. `ojdbc8.jar` is never present in the deployments folder, but if you unzip the `i2b2.war` you'll find the file `/WEB-INF/lib/ojdbc8.jar`. So it seems it is an issue from i2b2 side...
